### ISSUE TITLE
nginx: getting the fastcgi translation right

### ISSUE THREAD

**Issue by croth1** [matomo-org/docker#111]
Hi!

I am trying to get the translation between fast_cgi and http right. I am using the fpm docker image with docker-compose.

My nginx is communicating with the mamoto docker container on port 9000 and outputs http to 9001.

In principle this setting works, I can login and play around. But for some redirects the document root /var/www/html is prepended to the file and I get a 404 error.

E.g, if I log out, then try to log in again, the redirect is not to `https://analyticsserver.foo/index.php`, but `https://analyticsserver.foo/var/www/html/index.php`.  If I change the url in my browser manually to `https://analyticsserver.foo/index.php`, everything's fine and I can login.

Clearly something in my configuration is not right yet. Can you give me a clue where to look at?

<details>
<summary> nginx.conf</summary>

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
        worker_connections 768;
}

http {
  server {
        listen 9001;
        server_name     matomo_proxy;
        root /var/www/html;

        access_log      /var/log/nginx/access.log;
        error_log       /var/log/nginx/error.log;

        location / {
        }

        location ~\.php$ {
                fastcgi_param REQUEST_METHOD $request_method;
                fastcgi_param  QUERY_STRING       $query_string;
                fastcgi_param  REQUEST_METHOD     $request_method;
                fastcgi_param  CONTENT_TYPE       $content_type;
                fastcgi_param  CONTENT_LENGTH     $content_length;

                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

                fastcgi_pass matomo:9000;
        }
  }
}
```
</details>

<details>
<summary>docker-compose.yml</summary>

```
version: '2'

services:
  db:
    image: mysql:latest
    command: mysqld --user=root
    volumes:
      - ${MYSQL_DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  matomo:
    image: matomo:fpm
    volumes:
      - ${MATOMO_CONFIG}:/var/www/html/config:rw
      - ${LOG_FOLDER}:/var/www/html/logs
    links:
      - db

  nginx:
    image: nginx
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
    links:
      - matomo
    volumes_from:
      - matomo
    ports:
      - ${SERVER_HOST_PORT}:9001
```
</details>
