### ISSUE TITLE
Content-Type wrong for index.php with nginx fastcgi_pass

### ISSUE THREAD

**Issue by frederik-b** [matomo-org/docker#149]
Hi,

I'm trying to get a stupid simple Matomo/MariaDB/NginX setup to work in kubernetes.

So I set everything up, so that NginX and Matomo share a directory, Matomo unpacks eveything into that directory.
And Nginx serves static content and uses fastcgi_pass over tcp to serve the php stuff.

The problem is: the css and js loaded in the head
```
<link rel="stylesheet" type="text/css" href="index.php?module=Installation&amp;action=getInstallationCss&amp;cb=414e6446636be53ead622e94644af07e" />
<script type="text/javascript" src="index.php?module=Installation&amp;action=getInstallationJs&amp;cb=778f99c88bcf7d7201835ad99170f764"></script>
```
Get transfered as `content-type: text/html; charset=utf-8`

my nginx.conf looks something like this:
```
http {
  include    /etc/nginx/mime.types;
  index      index.php;

  # default_type application/octet-stream;

  sendfile        on;
  tcp_nodelay on;
  tcp_nopush on;

  server {
    listen         80 default_server;
    root           /var/www/html;

    location ~* \.php$ {
      include         fastcgi_params;
      fastcgi_pass    localhost:9000;
      fastcgi_index  index.php;
      fastcgi_param  HTTP_PROXY ""; # prohibit httpoxy: https://httpoxy.org/
      fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
      fastcgi_param  REQUEST_URI        $request_uri;
      fastcgi_param  DOCUMENT_URI       $document_uri;
      fastcgi_param  DOCUMENT_ROOT      $document_root;
      fastcgi_param  SCRIPT_FILENAME    $document_root$request_uri;
      fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
      fastcgi_param  CONTENT_TYPE       $content_type;
    }

    location / {
        try_files $uri $uri/ =404;
    }
  }
}
```
with irrelevant parts omitted (pid file, logging, ...)

why does matomo even serve css/js via the index.php?
and how do I make this work?

**Comment by frederik-b** [comment]
The same problem occurs with the unmodified apache image without fpm.
It looks to me like the docker images are just broken.
This in not a NginX problem, this is not my configuration.


These are the actual erros shown in the js console
```
Uncaught SyntaxError: Unexpected token <
menudropdown.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:20 Uncaught ReferenceError: angular is not defined
    at menudropdown.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:20
    at menudropdown.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:76
(anonymous) @ menudropdown.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:20
(anonymous) @ menudropdown.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:76
languageselector.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:14 Uncaught ReferenceError: angular is not defined
    at languageselector.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:14
    at languageselector.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:36
(anonymous) @ languageselector.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:14
(anonymous) @ languageselector.directive.js?cb=f0bdd1ff74ff2ec6de055251bfa73944:36
(index):240 Uncaught ReferenceError: $ is not defined
    at (index):240
```

The actual problem is, that
`http://matomo.development.finance-gate.de/index.php?module=Installation&action=getInstallationJs&cb=f0bdd1ff74ff2ec6de055251bfa73944`
and
`http://matomo.development.finance-gate.de/index.php?module=Installation&action=getInstallationCss&cb=414e6446636be53ead622e94644af07e`
are transported as `content-type: text/html; charset=utf-8
`

This is Matomo 3.8.1 from `https://hub.docker.com/_/matomo` regardless of flavour.

I think it's probably a bad idea to use index.php as a css and js resource in the first place but I didn't read the code.
Maybe it's just a missing php call to set the content type.

**Comment by Findus23** [comment]
Hi,

I'm not sure, but have you tried setting it up without docker to see if the bug is in Matomo or this docker image.

I am using Matomo [with nginx](https://github.com/matomo-org/matomo-nginx) without problems.

**Comment by frederik-b** [comment]
So I tried to run it locally
```
docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb:tag
docker run -d -p 80:80 --link some-mariadb:db matomo
```
and it runs fine
in kubernetes
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: matomo
  namespace: default
  labels:
    service: matomo
    LABEL_CONFIG: development
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: matomo
      LABEL_CONFIG: development
  replicas: 1
  template:
    metadata:
      labels:
        service: matomo
        LABEL_CONFIG: development
    spec:
      volumes:
        - name: matomo-app
          persistentVolumeClaim:
            claimName: development-matomo-app
        - name: matomo-db
          persistentVolumeClaim:
            claimName: development-matomo-db
      containers:
        - name: matomo-app
          image: matomo:3.8.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: matomo-app
              mountPath: "/data"
        - name: matomo-db
          image: mariadb:10.3.13
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: matomo-db
              mountPath: "/var/lib/mysql"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keys
                  key: "matomo.MYSQL_ROOT_PASSWORD"
```

it not only uses the wrong content-type but actually dosn't event render the js/css but outputs html when getting the aforementioned URLs:
`http://matomo.development.finance-gate.de/index.php?module=Installation&action=getInstallationJs&cb=f0bdd1ff74ff2ec6de055251bfa73944`
and
`http://matomo.development.finance-gate.de/index.php?module=Installation&action=getInstallationCss&cb=414e6446636be53ead622e94644af07e`

I am utterly confused.
Why does this behave so differently?
