### ISSUE TITLE
using another reverse proxy as Apache and Nginx

### ISSUE THREAD

**Issue by Ludea** [matomo-org/docker#154]
Hi,

I would like to use Traefik as a reverse proxy with docker compose.
I use `matomo:fpm` image and mariadb server.
```
 matomo:
  image: matomo:fpm
  links:
    - mariadb
  container_name: analytic
  restart: always
  volumes:
    - ./config:/var/www/html/config:rw
  networks:
    - web
    - internal
  labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:analytic.mydomain.com"
    - "traefik.port=9000"
    - "traefik.backend=matomo"
    - "traefik.frontend.entryPoints=http,https"

```

But I have Gateway timeout.
Does matomo image support Traefik ?
