### ISSUE TITLE
nginx: [emerg] host not found in upstream "app:9000" in /etc/nginx/conf.d/default.conf:2

### ISSUE THREAD

**Issue by PavanYadala** [matomo-org/docker#176]
On running the docker-compose on AWS ECS, the system is throwing below error. Please let me know how to fix it?

nginx: [emerg] host not found in upstream "app:9000" in /etc/nginx/conf.d/default.conf:2

**Comment by renepardon** [comment]
I've setup a fresh instance as well with the example docker-compose.yml file (slightly modificated for my use cases ;) )
The problem is, that you need to tell the nginx container to depend on the app container:

```yaml
web:
  image: nginx:alpine
  depends_on:
    - app
  volumes:
  - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
```

@PavanYadala hope this helps you getting started :)

**Comment by GopiPacha1996** [comment]
I have same  issue i tried above setup but getting same issue

**Comment by mhellmeier** [comment]
There are several reasons for this error.
One solution is already mentioned by @renepardon. If you add the `depends_on` flag and still got the error, check if you renamed your matomo app service. If it looks like this:
```yaml
services:
  my-matomo-db:
    image: mariadb

  # [...]

  my-matomo-app:
    image: matomo:fpm-alpine

  # [...]

  my-matomo-web:
    image: nginx:alpine
```
Than you have to also adjust the [matomo.conf](https://github.com/matomo-org/docker/blob/master/.examples/nginx/matomo.conf) file. In this case, change the first part into:
```conf
upstream php-handler {
	server my-matomo-app:9000;
}
```
The important thing is that `my-matomo-app` has to be the same service name as defined in your `docker-compose.yml` file.
