### ISSUE TITLE
Clarify use of volumes for docker-compose examples

### ISSUE THREAD

**Issue by davidlemaitre** [matomo-org/docker#204]
About docker-compose.yml example for apache :

```
 app:
    image: matomo
    restart: always
    volumes:
#     - ./config:/var/www/html/config
#     - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - VIRTUAL_HOST=
    env_file:
      - ./db.env
    ports:
      - 8080:80
```

The volumes section contains 3 lines. It's confusing. Why are the two first ones commented ? Should I use both config and logs volumes or just the matomo one ? Is it a best practice to put whole matomo in a volume ?

This path `/var/www/html/logs` is wrong, should be fixed to `/var/www/html/tmp/logs`.
