### ISSUE TITLE
Support for Docker swarm secrets

### ISSUE THREAD

**Issue by Midnighter** [matomo-org/docker#214]
Hi,

Many Docker images now allow reading values such as passwords from a secret file. This is a very useful feature and is supported by MariaDB, for example. I was wondering if Matomo could support the same. As an example of a docker-compose configuration:

```yaml
secrets:
  root_password:
    file: ./secrets/root_password.txt
  maria_password:
    file: ./secrets/maria_password.txt
```

I can then make use of this in the MariaDB service

```yaml
    secrets:
    - root_password
    - maria_password
    environment:
    - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_password"
    - "MYSQL_DATABASE=${MYSQL_DATABASE:-matomo}"
    - "MYSQL_USER=${MYSQL_USER:-matomo}"
    - "MYSQL_PASSWORD_FILE=/run/secrets/maria_password"
```

I would like to be able to do the same for Matomo as follows:

```yaml
    secrets:
    - maria_password
    environment:
    - "MATOMO_DATABASE_PASSWORD_FILE=/run/secrets/maria_password"
```
