### ISSUE TITLE
Dockerised Matomo can't connect to MySQL DB

### ISSUE THREAD

**Issue by cansurmeli** [matomo-org/docker#230]
Hello.

I've a Dockerised setup on my VPS. It's based on the Nginx reverse proxy [setup](http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/). Other websites or apps connecting to this setup are working fine, however, I can't get Matomo to work. During the installation of Matomo, it can't connect to the database.

Here is my `docker-compose.yml` file. It's pretty much the same except that I made some minor adjustments for my reverse proxy setup.

```
version: "3"

services:
  db:
    image: mariadb
    container_name: matomo-db
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - matomo-db:/var/lib/mysql
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    container_name: matomo-app
    links:
      - db
    volumes:
      - matomo-app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: unless-stopped
    container_name: matomo-web
    volumes:
      - matomo-app:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    ports:
      - 9898:80
    environment:
      VIRTUAL_HOST: analytics.mydomain.com
      LETSENCRYPT_HOST: analytics.mydomain.com
      LETSENCRYPT_EMAIL: me@mydomain.com

volumes:
  matomo-db:
  matomo-app:

networks:
  default:
    external:
      name: nginx-proxy
```
If I output the logs of the above three containers, everything looks sound.

Currently, I get the following error during the `Database Setup` stage:

`Error while trying to connect to the database server: SQLSTATE[HY000] [1045] Access denied for user 'matomo'@'172.19.0.13' (using password: YES)`

The error message above makes sense since `172.19.0.13` is the internal IP of `matomo-app`. Whereas, it should be the IP of `matomo-db` with the value `172.19.0.12`. Right now, the Matomo app is trying to find the database in it's own container but does not go looking for the database container setup for it.

To my eye, everything looks fine in the Compose file and the Matomo app should be able to connect to the database. What am I missing here?

Thanks.

p.s. For security purposes, I'm setting the `MYSQL_ROOT_PASSWORD` variable for the `db` container in the `db.env` file. Actually, I'm confused as to why it's not done there in the [example](https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml) itself.

**Comment by cansurmeli** [comment]
Also, from time to time, the error changes to a `502 Bad Gateway` and I can't even access the installation process. The Matomo web container throws the following error:

`matomo-web | 2021/01/03 21:09:17 [error] 21#21: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.2, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.11:9000", host: "analytics.mydomain.com"`

**Comment by perelin** [comment]
Same issue here. Found a solution yet?

**Comment by cansurmeli** [comment]
@perelin Unfortunately, no changes yet.

It would be really nice if someone from Matomo could look into this! I looked at my setup and everything seems fine to me. I'm assuming it's a Matomo related issue.

A similar problem occurered [here](https://github.com/matomo-org/docker/issues/122) as well. And, I guess that's also a dead end as the author of the issue didn't share his solution.

**Comment by perelin** [comment]
So, I got it running. For me the trick was to remove the deprecated `link` statement [1] in 
`docker-compose.yml` [2] and renaming the used volume from `db` to `dbvol` to avoid any collisions with the network host naming, just in case.

If somebody can confirm that this fixes the issue for them as well I will submit a pull request.

```yaml
version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
#    links:
#      - db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

volumes:
  dbvol:
  matomo:
```

[1] https://docs.docker.com/compose/compose-file/compose-file-v3/#links
[2] https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml

**Comment by cansurmeli** [comment]
Hey. Glad you got it working. However, it's not working for me just yet.

My volume name for the database was already something unique: `matomo-db`. And even though I have the `link` statement in my issue description, my initial approach was without it since I know they're deprecated. I tried without it at first. Then I thought add them yet again if there is some Matomo related requirement for that statement.

**Comment by perelin** [comment]
Ok, it seems I also set MYSQL passwords and removed the docker mysql volume so it can be recreated by docker-compose up.

**Comment by cansurmeli** [comment]
I also tried setting the root MySQL password inside the Compose file before. Didn't work.

When you mentioned about deleting the volumes, I tried that as well just now while having the root MySQL password in the Compose file. Still, unsuccessful.

Although thanks for the effort! Appreciate it!

**Comment by AndyYangUK** [comment]
I have a similar issue, I'm using the apache version and I get the error "Error while trying to connect to the database server: SQLSTATE[HY000] [2002] Connection timed out". I've preset the variables in the docker-compose file, but no luck with connecting to the DB...

This is my template:

```
version: "2"

services:
  db:
    image: mariadb:latest
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
  matomo:
    image: matomo:latest
    restart: always
    volumes:
      - ${MATOMO_VOLUME}:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - ${PORT}:80
```

**Comment by el95149** [comment]
I've been getting the '502' errors while trying to set up a Matomo/nginx stack behind a Traefik2 proxy.

After a few trials, it seems than when I used the `matomo:4.1.1-fpm` and `nginx:1.19.7` images, instead of their alpine counterparts, things clicked together and it started working. Here's my docker compose, hope it helps someone (I'm not posting the nginx.conf file, it's exactly the same as the one found in the `.examples/nginx` repo directory).

```
version: "3.7"

services:
  db:
    image: mariadb:10.5.8
    networks:
      - private
    command: --max-allowed-packet=64MB
    volumes:
      - "${DIRECTORY}/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=<>
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=<>
      - MYSQL_DATABASE=matomo

  app:
    image: matomo:4.1.1-fpm
    depends_on:
      - db
    networks:
      - private
    environment:
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=<>
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      #- "${DIRECTORY}/config:/var/www/html/config"
      #- "${DIRECTORY}/logs:/var/www/html/logs"
      - "${DIRECTORY}/matomo:/var/www/html"

  web:
    image: nginx:1.19.7
    depends_on:
      - db
      - app
    networks:
      - private
      - proxy
    volumes:
      - "${DIRECTORY}/matomo:/var/www/html:ro"
      # see https://github.com/matomo-org/matomo-nginx
      - "${DIRECTORY}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.matomo.loadbalancer.server.port: "80"
        traefik.http.routers.matomo.rule: "Host(`${HOST_NAME}`)"
        traefik.http.routers.matomo.entrypoints: "web-secured"
        traefik.http.routers.matomo.tls.certresolver: "mytlschallenge"

networks:
  private:
  proxy:
    external: true
```

**Comment by el95149** [comment]
> I've been getting the '502' errors while trying to set up a Matomo/nginx stack behind a Traefik2 proxy.
> 
> After a few trials, it seems than when I used the `matomo:4.1.1-fpm` and `nginx:1.19.7` images, instead of their alpine counterparts, things clicked together and it started working. Here's my docker compose, hope it helps someone (I'm not posting the nginx.conf file, it's exactly the same as the one found in the `.examples/nginx` repo directory).
> 
> ```
> version: "3.7"
> 
> services:
>   db:
>     image: mariadb:10.5.8
>     networks:
>       - private
>     command: --max-allowed-packet=64MB
>     volumes:
>       - "${DIRECTORY}/db:/var/lib/mysql"
>     environment:
>       - MYSQL_ROOT_PASSWORD=<>
>       - MYSQL_USER=matomo
>       - MYSQL_PASSWORD=<>
>       - MYSQL_DATABASE=matomo
> 
>   app:
>     image: matomo:4.1.1-fpm
>     depends_on:
>       - db
>     networks:
>       - private
>     environment:
>       - MATOMO_DATABASE_ADAPTER=mysql
>       - MATOMO_DATABASE_HOST=db
>       - MATOMO_DATABASE_TABLES_PREFIX=matomo_
>       - MATOMO_DATABASE_USERNAME=matomo
>       - MATOMO_DATABASE_PASSWORD=<>
>       - MATOMO_DATABASE_DBNAME=matomo
>     volumes:
>       #- "${DIRECTORY}/config:/var/www/html/config"
>       #- "${DIRECTORY}/logs:/var/www/html/logs"
>       - "${DIRECTORY}/matomo:/var/www/html"
> 
>   web:
>     image: nginx:1.19.7
>     depends_on:
>       - db
>       - app
>     networks:
>       - private
>       - proxy
>     volumes:
>       - "${DIRECTORY}/matomo:/var/www/html:ro"
>       # see https://github.com/matomo-org/matomo-nginx
>       - "${DIRECTORY}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
>     deploy:
>       labels:
>         traefik.enable: "true"
>         traefik.http.services.matomo.loadbalancer.server.port: "80"
>         traefik.http.routers.matomo.rule: "Host(`${HOST_NAME}`)"
>         traefik.http.routers.matomo.entrypoints: "web-secured"
>         traefik.http.routers.matomo.tls.certresolver: "mytlschallenge"
> 
> networks:
>   private:
>   proxy:
>     external: true
> ```

Scratch the above, it just did it again, after I removed the stack and re-deployed it (without clearing out my volumes, I wanted to hold on to the data).... So, the issue still stands, as it seems, at least for me.

**Comment by dakotahp** [comment]
@cansurmeli The earlier suggestion from @perelin did work for me. Perhaps you have a slight variation that made it not work since I believe the real issue is the volume name being the same as the hostname, although I don't see how one could interfere with the other 🤷🏼‍♂️. In any case, here is what I have:

- Removed `links` from docker-compose file.
- Change name of DB volume to be distinct from db hostname (`dbvol`)
- Set `MYSQL_ROOT_PASSWORD` in the env file
- Set `MYSQL_PASSWORD` and `MATOMO_DATABASE_PASSWORD` to the same password, preferably something without special characters to rule out any issues.
- Spun down containers and removed old ones so the database would start back up with fresh credentials during setup.

This worked for me. I would suggest trying his suggestion verbatim in a separate folder and then working back from there since your network setup in the docker-compose file is a bit different from this repo's nginx example.

**Comment by cansurmeli** [comment]
@dakotahp Hey, I finally got it working! Thanks a bunch.

I tried everything you said before but your fourth option. I guess it was setting up `MYSQL_PASSWORD` and `MATOMO_DATABASE_PASSWORD` to the same password that fixed the problem.

**Comment by isaaclee0** [comment]
This worked for me too!

**Comment by BraianPita** [comment]
Just an extra note, the current docker-compose.yml file they showcase on the repo is missing a network. If you add to both the "app" and the "db" services to the same internal network, it will successfully connect.

This is my working docker compose file:

```yml
version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    env_file:
      - ./db.env
    networks:
      - matomo-network

  app:
    container_name: matomo
    image: matomo
    restart: always
    volumes:
#     - ./config:/var/www/html/config:z
#     - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    expose:
      - 80
    networks:
      - matomo-network
      - reverse-proxy-network

volumes:
  db:
  matomo:

networks:
  matomo-network:
  reverse-proxy-network:
    external: true

```
