### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by michaelr524** [matomo-org/docker#248]
I've updated from the web UI as it offered. 
But is this the right way?
How should an update be completed with docker-compose? (I'm using the nginx example)

**Comment by holzfelix** [comment]
I tried the update via the docker-compose. Changed Version. But UI still shows Version 3.4.1

**Comment by michaelr524** [comment]
Yep. Had the same issue.

**Comment by holzfelix** [comment]
Found the solution, go on settings, on top of the screen you find an button, search for updates.

**Comment by michaelr524** [comment]
Yeah @holzfelix that's what I meant that I updated from the web UI. Just asking if it's the right way or we should update it by pulling latest versions of the repo and rebuilding the docker images somehow.

**Comment by holzfelix** [comment]
yes thats the correct way of upgrading.

**Comment by Tideri-Tim2** [comment]
> 
> 
> Yep. Had the same issue.

I have the same issue too. Dockerfile updated, new image pulled and container started. But the UI shows the old version. How come? Is there some kind of cache I have to clear? Log out and in again did not help. Thanks.

**Comment by holzfelix** [comment]
you have to click on update manually

**Comment by holzfelix** [comment]
klick on settings  -> you have to click on the "Search for new versions" button 
![image](https://user-images.githubusercontent.com/6866699/130428168-db953b76-3cd0-46a6-ae3f-70ed2c2abfdf.png)

**Comment by Tideri-Tim2** [comment]
> 
> 
> klick on settings -> you have to click on the "Search for new versions" button
> ![image](https://user-images.githubusercontent.com/6866699/130428168-db953b76-3cd0-46a6-ae3f-70ed2c2abfdf.png)

Thanks for your answer. I'm running Matomo on a Kubernetes system with a persistant-volume. So I guess I have to do both. Dockerfile-Update and the automatical file update like you are showing it now.
Thanks for your help!

**Comment by holzfelix** [comment]
yes you have to do both.

**Comment by egraumann** [comment]
can somebody please explain how they would do the upgrade, from let's say 4.6.2->4.10.1 in this scenario:
- self hosted on AWS, running docker image in some container on ECS
- DB is running on RDS

cause what I am doing is when I deploy the new docker image in ECS, I get to the setup screen again but then the step to connect to the DB fails with 'ACCESS DENIED' for any newer version than 4.6.2.

Is the proposed suggestion now to 
- first do the update in the frontend so that DB knows about this new version
- then update docker container?

Why would that be necessary...and why do I get 'Access Denied' message? seems strange to me.

**Comment by psi-4ward** [comment]
So I did an update right now.... and ... it was wired.

1. `/var/www/html` is a volume https://github.com/matomo-org/docker/blob/master/Dockerfile-alpine.template#L89 so created a new container from an updated image still uses the old volume
2. The [entrypoint.sh Script](https://github.com/matomo-org/docker/blob/master/docker-entrypoint.sh#L33) checks if theres already a `matomo.php` and if not, it will copy the files from docker-image.

So what I did is just delete the volume, recreated the container and execute `./console core:update`
Ie `docker inspect matomo` => find the volume and do a `docker volume rm ......`

Never seen such a strange implementation of a docker image.

**Comment by JanMalte** [comment]
> This is somewhat blocked by [matomo-org/matomo#19151](https://github.com/matomo-org/matomo/issues/19151)

Could you explain how the linked issue is related to provide a simple docker based update process.
I can‘t see how this should solve the issue with the mounted Matomo source volume.

**Comment by cma-se** [comment]
My current solution is: I build the docker container as usual. So I have the new version under /usr/src. As the entry point prevent the use of the new version because it checks if the matomo.php is in the persistent volume. I attach a session to the running container and just execute the same commands like the entry point will do (cp from /usr/src and change owner) 
I think this is only a workaround but I can't use the webupdater. Maybe I will use an updater container which has a different entry-point.
Did anyone see a problem in this approach?

**Comment by routmoute** [comment]
Simply remove `matomo.php` and restart the container with a new Matomo image works well for me.

**Comment by exetico** [comment]
I totally agree here. It's odd that Matomo doesn't really handle this as well, compared to other similar solutions. A pull of the image(s) and a restart of the container, should indeed secure the newest version.

I've noted the tip from routmounte, so I'm simple execuing a:
```bash=
docker pull matomo && docker exec -it matomo-app-1 rm /var/www/html/matomo.php && docker restart matomo-app-1
```
(edit the context for docker-compose, or whatever you'd like)

Which did the trick for me...

**Comment by FuckingToasters** [comment]
You should eb able to update it like any other docker image (make sure you use :latest tag in the image section of your compose file and then just redeploy it whenever there is a new version) alternativly you can use something like https://containrrr.dev/watchtower/ to automaate the update process for multiple running containers.

**Comment by maurerle** [comment]
This issue is still unsolved.

I run matomo with docker compose using:

```yml
services:
  matomo-db:
    image: mariadb:10
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./data/matomo-db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=matomo
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MARIADB_ROOT_PASSWORD=matomo

  matomo-app:
    image: matomo:fpm-alpine
    restart: always
    depends_on:
      - matomo-db
    volumes:
      - ./data/matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - PHP_MEMORY_LIMIT=2048M
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo
      - MATOMO_DATABASE_DBNAME=matomo

  matomo-web:
    image: nginx:alpine
    restart: always
    depends_on:
      - matomo-app
    volumes:
      - ./data/matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./conf/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:8080:80/tcp"
```

1. Just updating the docker did not help.
2. Updating with the UI inside the container did not help as well, as it only "updated" to the last 4.x version.
3. running `docker compose exec matomo-app sh` and then `./console core:update` did work, but not do anything as well
4. I had to run

```bash
docker compose pull
docker compose exec matomo-app rm /var/www/html/matomo.php
docker compose down
docker compose up -d
```

just as @exetico did mention.

**Comment by kaorukobo** [comment]
`rm /var/www/html/matomo.php` forces `entrypoint.sh` to re-extract the source code from `/usr/src/matomo`. Since the source does not include the configuration file (`config/config.ini.php`), this allows for upgrading the application without overwriting your settings, apparently.

https://github.com/matomo-org/docker/blob/82fa89f13413cae2cc185416dce5ce4a6baeb618/docker-entrypoint.sh#L55C1-L55C60

However, this approach is problematic. While it appears to work, it fails to account for file deletions in upstream updates. Consequently, the application may not function correctly after such an upgrade.

Deleting the `/var/www/html` volume is not a viable alternative, as it removes both the configuration file and any custom plugins.

If you are not using custom plugins, a possible solution is to bind-mount the configuration file separately.

```yml
services:
  matomo:
    volumes:
      - matomo_app:/var/www/html/
      - ./matomo-config/config.ini.php:/var/www/html/config/config.ini.php

volumes:
  matomo_app:
```

With this setup, if you want to upgrade, the following steps should be sufficient:

```bash
# remove the container
docker compose down matomo
# upgrade the image
docker compose pull matomo
# backup your config for the case (see below)
cp ./matomo-config/config.ini.php ./matomo-config/config.ini.php.bak
# remove the entire /var/www/html, including plugins/ and tmp/
docker volume rm matomo_app
# upgrade the database
docker compose run --rm matomo ./console core:update
# recreate the container
docker compose up -d --force-recreate matomo
```

This process seems adequate.

However, there's a potential risk that `entrypoint.sh` might be modified in the future to overwrite `config/config.ini.php`. Mounting `config.ini.php` as read-only is not an option, as Matomo will complain. Therefore, keeping a backup of `config.ini.php` is crucial.
