### ISSUE TITLE
docker-compose: use tags

### ISSUE THREAD

**Issue by alexislefebvre** [matomo-org/docker#263]
In the examples, the Docker images don't specify a version: https://github.com/matomo-org/docker/blob/63bc1cfa0361154750ab9d6aa9f75cb3a11474e8/.examples/apache/docker-compose.yml#L5

If mariadb publish a new release that break backward compatibility (e.g. a new major release), people may have issues when pulling new versions.

I suggest to specify tags like this:

```
services:
  db:
    image: mariadb:10.7
    # …

  app:
    image: matomo:4.5-apache
```
