### ISSUE TITLE
Missing timezone

### ISSUE THREAD

**Issue by Ninos** [matomo-org/docker#268]
A timezone is missing in the php configuration. As default php uses UTC (wrong time in log-files, archives...). Normally it should be enough adding date.timezone = "*add content of /etc/timezone*" to php.ini-file in DOCKERFILE.

**Comment by cseufert** [comment]
You can also use the TZ environment variable, eg:

`docker run -e TZ=Australia/Melbourne ...`
or in docker-compose.yml
```
version: '3'
services:
  matomo:
    image: matomo:latest
    environment:
      - 'TZ=Australia/Melbourne'
...
```
