### ISSUE TITLE
question: an alternative strategy how to use the matomo docker image

### ISSUE THREAD

**Issue by nflow** [matomo-org/docker#272]
hey, i have a question regarding an alternative strategy how to use the matomo docker image.

as far as i have observed it, the matomo applicaiton is copied by the `entryscript.sh`, if the `matomo.php` is not present, to the `/var/www/html` folder. since matomo performs various changes to the applicaiton during runtime, e.g. plugins, misc and config. the application folder is mounted externally, to not lose our configuration. the problem with that behavior is that updating a docker image will have no effect on deployments. thats my assessment so far.

in order image updates affect the applicaiton itself i did a few changes. i decided to mount only:
- /var/www/html/config/config.ini.php
- /var/www/html/plugins
- /var/www/html/misc
each time i recreate the container all applications will be overwritten with the originals and the update of an image will affect the application itself. furthermore, i prefer to mount relevant configs and folders which make  backups more straight forward, in my opinion. i used our current installation in a test setup and switched to the proposed strategy and everything seems to work.

can you think of any issues that may come up doing it this way?

here is the compose file i used:
```
version: '3.9'

services:
  mysql:
    image: "mariadb"
    command: "--max-allowed-packet=64MB"
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: r00t_p4ssw0rd
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo

  matomo:
    image: "matomo:4.6"
    restart: "unless-stopped"
    volumes:
      - ./configs/php-matomo.ini:/usr/local/etc/php/conf.d/php-matomo.ini:ro
      - ./configs/config.ini.php:/var/www/html/config/config.ini.php
      - plugins:/var/www/html/plugins
      - misc:/var/www/html/misc
    networks:
      - "default" 

volumes:
  db:
  plugins:
  misc:
```
thanks and kind regards!
