### ISSUE TITLE
Can someone share setup with jwilder nginx? Failed to connect to plugins.matomo.org port 443 Operation timed out.

### ISSUE THREAD

**Issue by Born2Bake** [matomo-org/docker#273]
I have setup Matomo with jwilder nginx just for ease of use:

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/apps/nginx/conf.d:/etc/nginx/conf.d
      - /www/apps/nginx/vhost.d:/etc/nginx/vhost.d
      - /www/apps/nginx/html:/usr/share/nginx/html
      - /www/apps/nginx/certs:/etc/nginx/certs:ro
      - /www/apps/nginx/logs:/var/logs/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssl-generator:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    container_name: ssl-generator
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: admin@weecodelab.com
    volumes:
      - /www/apps/nginx/conf.d:/etc/nginx/conf.d
      - /www/apps/nginx/vhost.d:/etc/nginx/vhost.d
      - /www/apps/nginx/html:/usr/share/nginx/html
      - /www/apps/nginx/certs:/etc/nginx/certs:rw
      - /www/apps/nginx/logs:/var/logs/nginx
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db-mysql:
    container_name: matomo-db
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - /www/dbs/db-matomo:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend

  matomo:
    image: matomo:fpm-alpine
    container_name: matomo
    restart: always
    links:
      - db-mysql
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - /www/apps/matomo:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: db-mysql
      PHP_MEMORY_LIMIT: 2048M
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend

  matomo-web:
    image: nginx:alpine
    restart: always
    container_name: matomo_web
    volumes:
      - /www/apps/matomo:/var/www/html:ro
      - /www/apps/matomo-web/conf.d:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_MATOMO}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST_MATOMO}"
      VIRTUAL_PORT: 8085
    ports:
      - 8085
    networks:
      - frontend
      - backend
```

and it's kinda working fine, however, randomly getting `2022/01/25 22:08:21 [error] 34#34: *586 FastCGI sent in stderr: "PHP message: Error in Matomo: curl_exec: Failed to connect to plugins.matomo.org port 443 after 30202 ms: Operation timed out. Hostname requested was: plugins.matomo.org" while reading response header from upstream, client: 172.16.198.2, server: , request: "GET /index.php?` errors. Any advice on that one?
