### ISSUE TITLE
Allow non-root startup

### ISSUE THREAD

**Issue by CoaxVex** [matomo-org/docker#294]
Would it be possible to allow for a non-root startup?

On OpenShift (with a generated non-root uid) startup fails:

```
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: Exiting with failure status due to previous errors
```

**Comment by CoaxVex** [comment]
> What exactly are you using? It works for me using `docker run--user www-data`.

On OpenShift, the uid will be randomly generated, and the resulting user won't have write permission in /var/www/html. You can reproduce like this:


```
docker run --user 2000 matomo:latest
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwxr-xr-t: Operation not permitted
tar: Exiting with failure status due to previous errors
```



I got it working by mounting an emptyDir volume on /var/www/html. Also had to override the apache2 config to listen on port 8080:

```
[...]
        volumeMounts:
          - name: matomo-html
            mountPath: /var/www/html
          - name: matomo-apache2
            mountPath: /etc/apache2/ports.conf
            subPath: ports.conf
          - name: matomo-apache2
            mountPath: /etc/apache2/sites-available/000-default.conf
            subPath: 000-default.conf
      volumes:
        - name: matomo-html
          emptyDir: {}
        - name: matomo-apache2
          configMap:
            name: matomo
[...]
```


```
apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo
data:
  ports.conf: "Listen 8080"
  000-default.conf: |
    <VirtualHost *:8080>

      ServerAdmin webmaster@localhost
      DocumentRoot /var/www/html

      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined

    </VirtualHost>
```
