### ISSUE TITLE
Auto-archiving for reports (using cron jobs) is enabled in docker image?

### ISSUE THREAD

**Issue by carromeu** [matomo-org/docker#298]
The [automatic proccess to archive reports](https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/), using command line call to `console` and _Cron_, is enable inside image or I need to set another service in stack of containers to activate it?

**Comment by maathimself** [comment]
I don't believe cron is set to run in the containers. I have add the following command to the host to get cron archiving every hour.
Edit the crontab file ( /etc/crontab )
Then paste the following at the bottom

*    1 * *   docker exec -u www-data matomo_app_1 php console core:archive

Its not the best way to do it but it works for me.

**Comment by cseufert** [comment]
You can use docker-compose something like this:
```yaml
# docker-compose.yaml
version: '3'
services:
  matomo:
    image: matomo
    user: "1362"
    restart: always
    environment:
     - 'MATOMO_DATABASE_HOST=db
     - ...
    volumes:
      - /home/matomo/data:/var/www/html
      - /home/matomo/php-fpm:/run/php-fpm
    ports:
      - '127.0.0.1:29000:9000'
  cron:
    image: matomo
    user: "1362"
    restart: always
    environment:
     - 'MATOMO_DATABASE_HOST=db
     - ...
    volumes:
      - /home/matomo/data:/var/www/html
    depends_on: [matomo]
    entrypoint:  "sh -c 'while true; do php console core:archive --url=https://matomo.udo.net.au/; sleep 600; done'"
```
