### ISSUE TITLE
Error: Matomo is already installed.  Original error was "Mysqli prepare error: Table 'matomo.matomo_option' doesn't exist".

### ISSUE THREAD

**Issue by FuckingToasters** [matomo-org/docker#340]
However, now when visiting the site there is a new issue (nothing about it shows in the logs tho)

Hello, i had an issue where i wanted to update portainer so i downloaded the backup first but it not seem to have successfully downloaded and i only noticed that after the update, all containers were still running but i couldn't manage the stacks within the new portainer installation due to the error "this stack was created outside of portainer, control over it is limited"

Now i copy the env info etc shown in the running containers and make a new compose file out of it to add in an new stack.

Now i tried to do this process with matomo, which then after visiting the site caused following issue:
![image](https://github.com/matomo-org/docker/assets/94435104/dbbe9994-6898-4843-a395-684b84a8bed7)

There are no erros shown in matomo or database logs, i guess i somehow need to set it so it uses the matomo files from the existing installation and not try to start a new installation process; i don't know how to do so tho.

Note: the go back to matomo just refresh the homepage on which the error happens, statuscode in netrequests is 400

Here the docker-compose.yml file:
```yml
version: '3.0'

services:
  matomo:
    image: matomo:latest
    command: apache2-foreground
    entrypoint: /entrypoint.sh
    environment:
      - APACHE_CONFDIR=/etc/apache2
      - APACHE_ENVVARS=/etc/apache2/envvars
      - GPG_KEYS=528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD
      - MATOMO_DATABASE_ADAPTER=MYSQLI
      - MATOMO_DATABASE_CHARSET=utf8mb4
      - MATOMO_DATABASE_CONNECT_TIMEOUT=60
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_ENABLE_SSL=0
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_PASSWORD=REDACTED
      - MATOMO_DATABASE_PORT=3306
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=InfinityMonster
    volumes:
       # - ./config:/var/www/html/config:z
       # - ./logs:/var/www/html/logs:z
      - data:/var/www/html:z
    restart: always
    networks:
      webproxy:
        ipv4_address: 172.26.0.10

  db:
    image: jc21/mariadb-aria:latest
    command: null
    entrypoint: /scripts/run.sh
    environment:
      - MYSQL_DATABASE=matomo
      - MYSQL_PASSWORD=REDACTED
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_USER=InfinityMonster
    volumes:
      - db:/var/lib/mysql:Z
    networks:
      webproxy:
        ipv4_address: 172.26.0.202

networks:
  webproxy:
    external: true

volumes:
  db:
  data:
  ```
