### ISSUE TITLE
Does not work - Cannot connect to DB

### ISSUE THREAD

**Issue by cosad3s** [matomo-org/docker#353]
I use the nginx configuration.

**Attempt 1:**  `docker-compose up` - first error is `db-1   | 2024-03-04 11:04:15+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
db-1   |        You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ROOT_PASSWORD_HASH, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD`

**Attempt 2:** set `MARIADB_ROOT_PASSWORD=matomodb` in `db.env`, then after trying to connect on the page [http://localhost.:8080/index.php?action=databaseSetup](http://localhost.:8080/index.php?action=databaseSetup), I got an error:

- *Impossible de se connecter au serveur de la base de données: Accès à la base de données refusé*
- In Docker logs: `db-1   | 2024-03-04 11:05:28 6 [Warning] Access denied for user 'matomo'@'%' to database 'matomo'`

*In the meantime, I had to use another docker-compose.yml sample from this blogpost, if anyone is interested (just update the Matomo version) [https://datmt.com/backend/running-matomo-using-docker-compose/](https://datmt.com/backend/running-matomo-using-docker-compose/)*

**Comment by cosad3s** [comment]
I have tested with following `db.env`:

```bash
MYSQL_PASSWORD=matomodb
MYSQL_DATABASE=matomodb
MYSQL_USER=matomo
MATOMO_DATABASE_ADAPTER=mysql
MATOMO_DATABASE_TABLES_PREFIX=matomo_
MATOMO_DATABASE_USERNAME=matomo
MATOMO_DATABASE_PASSWORD=matomodb
MATOMO_DATABASE_DBNAME=matomo
MARIADB_AUTO_UPGRADE=1
MARIADB_INITDB_SKIP_TZINFO=1
MARIADB_ROOT_PASSWORD=matomodb
MYSQL_ROOT_PASSWORD=matomodb
```

No success.

But anyway, I found another way to run Matomo in Docker with following Docker Compose:

```yml
version: "3"

services:
  matomo_db:
    image: mariadb:10.6
    container_name: matomo_db
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - /app/data/matomo/db:/var/lib/mysql
    env_file: 
      - ./matomo.env 

  matomo_app:
    image: matomo:4.11.0-apache
    container_name: matomo_app
    restart: always
    depends_on: 
      - matomo_db
    volumes:
      - /app/data/matomo/web:/var/www/html

    env_file: 
      - ./matomo.env 

    ports:
      - 8080:80
```

And configuration `matomo.env`:

```bash
MYSQL_ROOT_PASSWORD=REDACTED
MYSQL_DATABASE=matomo_tracking
MATOMO_DATABASE_HOST=matomo_db
MATOMO_DATABASE_USERNAME=root
MATOMO_DATABASE_PASSWORD=REDACTED
MATOMO_DATABASE_DBNAME=matomo_tracking
```
