### ISSUE TITLE
Cannot access config.ini.php

### ISSUE THREAD

**Issue by mynona** [matomo-org/docker#365]
My matomo installation cannot access config.ini.php behind nginx

```
<details>
<summary>Click to view System Check</summary>

### Mandatory checks

#### PHP-Version >= 7.2.5:
 ✔ 8.2.22

#### PDO Erweiterung:
 ✔ 

#### PDO\MYSQL Erweiterung:
 ✔ 

#### MYSQLI Erweiterung:
 ✔ 

#### Weitere erforderliche Anforderungen:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### Erforderliche Funktionen:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### Benötigte PHP Konfiguration (php.ini):
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### Verzeichnisse mit Schreibzugriff:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c


### Optional checks

#### Verzeichnisse, welche privat sein müssen:
 ⚠ Warning: Überprüfung der URL $MATOMO_URLconfig/config.ini.php ist fehlgeschlagen: curl_exec: Connection timed out after 2000 milliseconds. Hostname requested was: www.example.de ⚠ Warning: Überprüfung der URL $MATOMO_URLtmp/cache/tracker/matomocache_general.php ist fehlgeschlagen: curl_exec: Connection timed out after 2001 milliseconds. Hostname requested was: www.example.de ✔ Alle privaten Verzeichnisse sind nicht aus dem Internet zugänglich.

#### Empfohlene private Verzeichnisse:
 ⚠ Warning: Überprüfung der URL $MATOMO_URLtmp/ ist fehlgeschlagen: curl_exec: Connection timed out after 2001 milliseconds. Hostname requested was: www.example.de ⚠ Warning: Überprüfung der URL $MATOMO_URLtmp/empty ist fehlgeschlagen: curl_exec: Connection timed out after 2001 milliseconds. Hostname requested was: www.example.de ⚠ Warning: Überprüfung der URL $MATOMO_URLlang/en.json ist fehlgeschlagen: curl_exec: Connection timed out after 2000 milliseconds. Hostname requested was: www.example.de ✔ Alle privaten Verzeichnisse sind nicht aus dem Internet zugänglich.

#### Dateiintegrität:
 ✔ 

#### 64-bit PHP Binär:
 ✔ 

#### Tracker-Status:
 ✔ 

#### Speicherlimit:
 ✔ 2048M

#### Zeitzone:
 ✔ 

#### Öffnen einer URL:
 ✔ curl

#### PageSpeed ist deaktiviert:
 ✔ 

#### GD > 2.x + FreeType (Grafiken):
 ✔ 

#### Andere Erweiterungen:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### Andere Funktionen:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### Dateisystem:
 ✔ 

#### Cron einrichten (schnelleres Laden von Berichten):
 ⚠ Warning: Für eine optimale Leistung und ein schnelles Matomo wird dringend empfohlen, einen Crontab einzurichten, um Ihre Berichte automatisch zu archivieren und das Auslösen durch den Browser in den Matomo-Einstellungen zu deaktivieren. Erfahren Sie mehr.

#### Cron einrichten - Prozesse via CLI steuern:
 ✔ OK

#### Datenbankfähigkeiten:
 ✔ UTF8mb4 charset ⚠ Warning: LOAD DATA INFILE<br/>Tipp: Wenn Sie LOAD DATA INFILE verwenden, indem Sie Ihre PHP- und MySQL-Software aktualisieren und sicherstellen, dass Ihr Datenbankbenutzer das FILE-Recht hat, wird der Archivierungsprozess von Matomo erheblich beschleunigt.<br/>Sie sollten dieses Problem beheben, wenn Ihr Matomo-Server Webseiten mit hohem Traffic (z.B. über 100.000 Seitenansichten pro Monat) verarbeiten muss. ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

#### Maximale Packetgröße:
 ✔ 

#### Erzwungene SSL Verbindung:
 ✔ 

#### Standorterkennung:
 ✔ geoip2php (continent_code, continent_name, country_code, country_name, region_name, city_name, lat, long)

#### Update über HTTPS:
 ✔ 

#### Mobile Messaging SMS Provider:
 not configured

#### Schreibbarer JavaScript-Tracker ("/matomo.js"):
 ✔ 


### Informational results

#### Matomo Version:
 5.1.1

#### Matomo Update History:
 4.15.1,4.14.1,

#### Matomo Install Version:
 4.14.1

#### Latest Available Version:
 5.1.1

#### Is Git Deployment:
 0

#### PHP_OS:
 Linux

#### PHP SAPI:
 apache2handler

#### Timezone Version:
 2024.1

#### PHP Timezone:
 UTC

#### PHP Time:
 1726318388

#### PHP Datetime:
 2024-09-14 12:53:08

#### PHP INI max_execution_time:
 30

#### PHP INI post_max_size:
 8M

#### PHP INI max_input_vars:
 1000

#### PHP INI zlib.output_compression:
 0

#### Curl Version:
 7.88.1, OpenSSL/3.0.13

#### Suhosin Installed:
 0

#### DB Prefix:
 matomo_

#### DB Charset:
 utf8mb4

#### DB Adapter:
 MYSQLI

#### MySQL Version:
 11.5.2-MariaDB-ubu2404

#### Num Tables:
 75

#### Browser Segment Archiving Enabled:
 1

#### Development Mode Enabled:
 0

#### Internet Enabled:
 1

#### Multi Server Environment:
 0

#### Auto Update Enabled:
 1

#### Custom User Path:
 0

#### Custom Include Path:
 0

#### Release Channel:
 latest_stable

#### Plugins Activated:
 API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomDimensions, CustomJsTracker, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, JsTrackerInstallCheck, LanguagesManager, Live, Login, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Proxy, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

#### Plugins Deactivated:
 DBStats, MobileAppMeasurable, TagManager

#### Plugins Invalid:
 

#### Server Info:
 Apache/2.4.61 (Debian)

#### Had visits in last 1 day:
 1

#### Had visits in last 3 days:
 1

#### Had visits in last 5 days:
 1

#### Archive Time Last Started:
 -

#### Archive Time Last Finished:
 -

#### User Agent:
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15

#### Browser Language:
 de-de,de

#### Total Invalidation Count:
 282

#### In Progress Invalidation Count:
 0

#### Scheduled Invalidation Count:
 282

#### Earliest invalidation ts_started:
 

#### Latest invalidation ts_started:
 

#### Earliest invalidation ts_invalidated:
 2023-04-18 08:31:59

#### Latest invalidation ts_invalidated:
 2024-09-14 08:22:01

#### Number of segment invalidations:
 26

#### Number of plugin invalidations:
 0

#### List of plugins being invalidated:
 

#### Anonymize Referrer:
 

#### Do Not Track enabled:
 1

</details>
```

**Comment by mynona** [comment]
This is what I am referring to:

 ⚠ Warning: Überprüfung der URL $MATOMO_URLconfig/config.ini.php ist fehlgeschlagen: curl_exec: Connection timed out after 2000 milliseconds. Hostname requested was: www.example.de ⚠ Warning: Überprüfung der URL $MATOMO_URLtmp/cache/tracker/matomocache_general.php ist fehlgeschlagen: curl_exec: Connection timed out after 2001 milliseconds. Hostname requested was: www.example.de ✔ Alle privaten Verzeichnisse sind nicht aus dem Internet zugänglich.

**Comment by mynona** [comment]
docker-compose:

```
  db-matomo:
    container_name: database-matomo
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_DATABASE=matomo
      - MARIADB_PASSWORD=pwd
      - MARIADB_ROOT_PASSWORD=pwd
      - MYSQL_TCP_PORT=3308
    ports:
      - 3308:3308
    expose:
      - 3308
    volumes:
      - mysql-matomo-data:/var/lib/mysql
    command: --max-allowed-packet=64MB
    
  matomo:
    container_name: matomo
    image: matomo:latest
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_DATABASE=matomo
      - MARIADB_PASSWORD=pwd
      - PHP_MEMORY_LIMIT=2048M
    ports:
      - 28080:80
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - ./data/matomo:/var/www/html
      - "geoip-updater:/data/geoip"
```
